# Generated by Django 5.2 on 2025-04-18 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barbeiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("foto", models.ImageField(upload_to="barbeiros", verbose_name="Foto")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Barbeiro",
                "verbose_name_plural": "Barbeiros",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("corte", "Corte de Cabelo"),
                            ("barba", "Barba"),
                            ("bigode", "Bigode"),
                            ("combo", "Combo (Corte + Barba)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Preço"
                    ),
                ),
                (
                    "duracao",
                    models.IntegerField(default=30, verbose_name="Duração (minutos)"),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("horario", models.TimeField(verbose_name="Horário")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_agendamento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Agendamento"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="usuarios.profile",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "barbeiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="agendamentos.barbeiro",
                        verbose_name="Barbeiro",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="agendamentos.servico",
                        verbose_name="Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "unique_together": {("barbeiro", "data", "horario")},
            },
        ),
    ]
